### ISSUE TITLE
Hide items until a certain number of characters are entered into search

### ISSUE THREAD

**Issue by mdavo6** [esentis/multiple_search_selection#51] opened 2024-04-05 02:38 UTC
## Describe the feature you'd like

Firstly thank you for the excellent widget, we use it throughout our app.

Our use case is to add a user to a project. There is a list of all users who have signed up to the app that they can select from, however from a privacy perspective we do not want the user to be able to see all users. The list of users should be hidden and only show up when the user has entered a number of characters into the search field (lets say 3). It feels like there should be a simple way to add this functionality, for example with a new `itemVisibility` option (for example `ShowedItemsVisibility.onEntered(3)`).

## Describe alternatives you've considered

I have tried working with `onSearchChanged` using the new `multipleSearchController`, and considered editing the text entered into `SearchField`, but I feel like I am fighting with the existing code and can't seem to find a simple solution. Perhaps I am overlooking something?

Thanks again!

**Comment by esentis** [comment] 2024-04-05 08:50
Hello @mdavo6 and thanks for taking the time to fill the feature request :) 

Indeed there is no straightforward way to do this with the current version, but it will be nice addition !
I'll work on it asap, prolly this weekend.

Cheers !

**Comment by mdavo6** [comment] 2024-04-05 10:29
No worries @esentis . I'm glad it was not just me missing something. That would be fantastic. Thank you!

**Comment by esentis** [comment] 2024-04-05 20:58
I've added `minCharsToShowItems` parameter to `MultipleSearchController` to delay the search operation until the user has typed a minimum number of characters as requested with version `2.6.4` !

**Comment by martinogarrizzo5** [comment] 2024-08-12 13:54
Hi, It look like the `minCharsToShowItems` property doesn't work with the `MultipleSearchSelection<T>.overlay` constructor.
Can anyone check if i'm wrong about it?
Here's a sample component i created
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:multiple_search_selection/createable/create_options.dart';
import 'package:multiple_search_selection/multiple_search_selection.dart';
import 'package:multiple_search_selection/overlay/overlay_options.dart';

class MultiSearchField<T> extends StatefulWidget {
  final List<T> items;
  final List<T> initialPickedItems;
  final Widget Function(T) getItemLabel;
  final Widget Function(T) getPickedItemLabel;
  final T Function(String) onCreateOption;
  final String Function(T) fieldToCheck;
  final String placeholder;
  final IconData? suffixIcon;
  final MultipleSearchController? controller;
  final int? maxSelectedItems;

  const MultiSearchField({
    super.key,
    required this.items,
    required this.initialPickedItems,
    required this.getItemLabel,
    required this.getPickedItemLabel,
    required this.onCreateOption,
    required this.fieldToCheck,
    this.placeholder = "Search",
    this.suffixIcon,
    this.controller,
    this.maxSelectedItems,
  });

  @override
  State<MultiSearchField<T>> createState() => _MultiSearchFieldState();
}

class _MultiSearchFieldState<T> extends State<MultiSearchField<T>> {
  @override
  Widget build(BuildContext context) {
    final customStyles = Theme.of(context).extension<CustomStyles>()!;
    final l10n = S.of(context)!;

    return MultipleSearchSelection<T>.overlay(
      controller: widget.controller,
      maximumShowItemsHeight: 200,
      clearSearchFieldOnSelect: true,
      placePickedItemContainerBelow: true,
      items: widget.items,
      initialPickedItems: widget.initialPickedItems,
      showClearAllButton: false,
      showSelectAllButton: false,
      noResultsWidget: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(6),
            color: Colors.white,
          ),
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(l10n.noResults),
          ),
        ),
      ),
      showedItemsBoxDecoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(6),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      pickedItemsBoxDecoration: BoxDecoration(),
      pickedItemsContainerMaxHeight: 1000,
      maxSelectedItems: widget.maxSelectedItems,
      searchField: TextField(
        decoration: InputDecoration(
          labelText: widget.placeholder,
          suffixIcon: widget.suffixIcon != null
              ? IconButton(
                  onPressed: null,
                  color: Theme.of(context).colorScheme.secondary,
                  disabledColor: Theme.of(context).colorScheme.secondary,
                  padding: const EdgeInsets.symmetric(horizontal: 24),
                  icon: Icon(
                    widget.suffixIcon,
                    size: 28,
                  ),
                )
              : null,
        ),
      ),
      overlayOptions: OverlayOptions<T>(
        canCreateItem: true,
        closeOnItemSelected: true,
        createOptions: CreateOptions<T>(
          create: widget.onCreateOption,
          createBuilder: (text) => Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(6),
                color: Colors.white,
              ),
              child: Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 16.0,
                  horizontal: 12,
                ),
                child: Text("${l10n.outOfList}: $text"),
              ),
            ),
          ),
          pickCreated: true,
        ),
      ),
      fieldToCheck: widget.fieldToCheck,
      itemBuilder: (item, index, isPicked) {
        return Padding(
          padding: const EdgeInsets.fromLTRB(6, 6, 6, 0),
          child: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(6),
              color: Colors.white,
            ),
            child: Padding(
              padding: const EdgeInsets.symmetric(
                vertical: 16.0,
                horizontal: 12,
              ),
              child: widget.getItemLabel(item),
            ),
          ),
        );
      },
      pickedItemBuilder: (item) {
        return Container(
          decoration: BoxDecoration(
            color: customStyles.colors.primary,
            border: Border.all(
              color: customStyles.colors.inputBackground,
            ),
          ),
          child: Padding(
            padding: const EdgeInsets.all(6),
            child: widget.getPickedItemLabel(item),
          ),
        );
      },
    );
  }
}

```

**Comment by esentis** [comment] 2024-08-12 13:56
@martinogarrizzo5 hello there ! Will look into it and get back at you asap.

**Comment by martinogarrizzo5** [comment] 2024-08-12 14:23
It seems also that calling the `getPickedItems` method of the `MultipleSearchController` returns an empty list. Can you also check that? Thanks

**Comment by esentis** [comment] 2024-08-12 15:01
@martinogarrizzo5 you were right about the `minCharsToShowItems` on Overlay. There was a bug and will be fixed with the next version. However, I cant reproduce the second issue with `getPickedItems`

**Comment by martinogarrizzo5** [comment] 2024-08-12 18:01
Here is the snippet of code that i wrote related to the component i sent you in the previous comments. Can you give it a look? Thanks

Tell me if it is understandable. I know there are variables that i didn't specified because i cannot share the other parts of the code for privacy reason. I apologize for the unconvenience.

```dart
MultiSearchField<Commission>(
                    maxSelectedItems: 1,
                    items: _availableCommissions,
                    controller: _commissionFieldController,
                    fieldToCheck: (commission) => commission.id,
                    initialPickedItems:
                        widget.commission != null ? [widget.commission!] : [],
                    placeholder: l10n.commissionPlaceholder,
                    suffixIcon: Icons.person,
                    error: _commissionError,
                    getItemLabel: (commission) => Text(commission.id),
                    onPickedChange: (list) => setState(() {
                      _commissionError = null;
                    }),
                    onCreateOption: (text) => Commission(id: text, name: ""),
                    getPickedItemLabel: (commission) => Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        if (commission.name.isNotEmpty)
                          Icon(
                            Icons.work,
                            color: customStyles.colors.onPrimary,
                          ),
                        const Gap(4),
                        Text(
                          commission.id,
                          style: customStyles.labelStyle.copyWith(
                            color: customStyles.colors.onPrimary,
                          ),
                        ),
                        const Gap(4),
                        Icon(
                          Icons.close,
                          size: 16,
                          color: customStyles.colors.onPrimary,
                        ),
                      ],
                    ),
                  ),
```

**Comment by martinogarrizzo5** [comment] 2024-08-12 18:11
or maybe look at this implementation that should be easier and doesn't use any wrapper:

```dart
MultipleSearchSelection<Commission>(
                    controller: _commissionFieldController,
                    items: _availableCommissions,
                    searchField: TextField(),
                    fieldToCheck: (commission) {
                      return commission.id;
                    },
                    itemBuilder: (commission, index, isPicked) {
                      return Text(commission.id);
                    },
                    pickedItemBuilder: (commission) {
                      return Text(
                        commission.id,
                        style: customStyles.labelStyle.copyWith(
                          color: customStyles.colors.onPrimary,
                        ),
                      );
                    },
                  ),
```

**Comment by esentis** [comment] 2024-08-13 11:49
@martinogarrizzo5 I don't see anything weird but I can't see where you are calling the `getPickedItems` method either.

**Comment by martinogarrizzo5** [comment] 2024-08-13 13:33
I'm sorry. Thank you for the time you're spending. I created a button inside a row in the same tree level that when is pressed it fires the following function:

```dart
  List<Commission> _pickedCommissions = [];
  final _commissionFieldController = MultipleSearchController<Commission>(
    minCharsToShowItems: 3,
  );
  String? _commissionError;

  List<Site> _pickedSites = [];
  final _sitesFieldController = MultipleSearchController<Site>(
    minCharsToShowItems: 3,
  );
  String? _sitesError;

Future<void> _saveForm() async {
    if (_commissionFieldController.getPickedItems().isEmpty) {
      setState(() => _commissionError = "field required");
    }
    if (_sitesFieldController.getPickedItems().isEmpty) {
      setState(() => _sitesError = "field required");
    }
  }
```

**Comment by esentis** [comment] 2024-08-13 13:44
Hmm, the provided snippet should be working. 
Would be super helpful if you could reproduce the same bug with the provided examples.

**Comment by martinogarrizzo5** [comment] 2024-08-13 14:36
Using the pieces of code that i provided to you, it didn't work. I instead found a workaround using the `onPickedChange` property of the `MultipleSearchSelection` widget and providing a function that updates a local variable with the current list. So in this way in the `_saveForm` function I just check my list instead of using the `getPickedItems` method. 
Can you tell me if this is a reasonable solution? Thanks

**Comment by esentis** [comment] 2024-08-13 15:22
Yes your workaround is fine, but I still don't understand why the `getPickedItems ` is not firing for you :<

**Comment by martinogarrizzo5** [comment] 2024-08-13 18:22
You mean the `getPickedItems`, right? Anyway, for now I'm ok with this solution. For me, you can close the issue. I will open another when I'll have the time to investigate more or when I'll have other questions about the library. 
Thanks for the help

**Closed as completed** 2024-08-13 18:23 UTC
Labels: bug, under investigation
